esphome:
  name: xantrex
  platform: ESP8266
  board: d1_mini
  includes:
    - xantrex.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

ota:

mqtt:
  broker: 192.168.0.6
  username: mosquitto

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: D4
  rx_pin: D3

sensor:
  - platform: custom 
    lambda: |-
      auto my_xantrex = new Xantrex(id(uart_bus));
      App.register_component(my_xantrex);
      return {my_xantrex->kwhlife_sensor, my_xantrex->kwhtoday_sensor,
        my_xantrex->pin_sensor, my_xantrex->pout_sensor,
        my_xantrex->vin_sensor, my_xantrex->vout_sensor,
        my_xantrex->iin_sensor, my_xantrex->iout_sensor,
        my_xantrex->freq_sensor, my_xantrex->time_sensor, my_xantrex->temp_sensor,
        };
      
    sensors:
    - name: "PV kwh life"
      unit_of_measurement: "kWh"
      accuracy_decimals: 0
    - name: "PV kwh today"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
    - name: "PV power in"
      unit_of_measurement: "W"
      accuracy_decimals: 0
    - name: "PV power out"
      unit_of_measurement: "W"
      accuracy_decimals: 0
    - name: "PV volts in"
      unit_of_measurement: "V"
      accuracy_decimals: 1
    - name: "PV volts out"
      unit_of_measurement: "V"
      accuracy_decimals: 1
    - name: "PV current in"
      unit_of_measurement: "A"
      accuracy_decimals: 2
    - name: "PV current out"
      unit_of_measurement: "A"
      accuracy_decimals: 2
    - name: "PV frequency"
      unit_of_measurement: "Hz"
      accuracy_decimals: 3
    - name: "PV time"
      unit_of_measurement: "seconds"
      accuracy_decimals: 0
    - name: "PV temp"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
